# Generated by Django 3.1.2 on 2020-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='watcher',
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='qtzCPwBoKSBBPmMHmQUpWeALRzoCwCrBiDtwbLKgaZuupsaXpHZGDEIwvIMLWMFaMNSTGY', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='DcPuVFwnVrQamvOwHOEJEmxQEtWzTSJSLVTDygpazOPzWFabHWLNZoxpBhIMFsWuZzEixV', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='LidoCeLXpFFctAYhPnvBIGnApZwXETJAKfKjgWIBTCtodAONfvmrodXuFiwXkYOVZBykqA', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='NYgiWokdUabwiNneuqTElGLnAqPxKFhOkGLnwUNUCKhseBvMJMQlviITTyhUbfvavmPEzS', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.Watch'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='RAafjOuQKQpkGiNQegfHtcfxTklpiOZEMSvXLYCxcpTmfLdbGULDvZDjpivkCyHPTJQmlD', max_length=150, primary_key=True, serialize=False),
        ),
    ]
