# Generated by Django 3.1.2 on 2020-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201020_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='name',
            field=models.CharField(default='watch/', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='uMfEOywSXkPwNpYvcUSsCMqDAQFAgaJTAFxIbojlIgWVKYjaeAGTCHpShXHaSUhuubLWfN', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='wXvvoXZZyAoFGLFBSnzdkciPDHYodqSdkgfUKMLZRTujQEMFSqmSOtcbAlpJPmzdFfMfEW', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='kbBJfsLPHuHjkgkQoYxJmcUvONiIpINGwoUeCKGWJzDeVAQDyABfEBlXCWItoozgUjtuJd', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='bffBZsLCWohacKydhZQCyzuyRvYuLeTxGPHkoMMlQMrrnfcEgNTskacFuyASjkRTMxYGnN', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='VIehmqNaasTwukdHwbYRLuiJXEMulsoelXfcPFBhVMEPVYkIvQjeNFaRrdqzwTEJoLqdCZ', max_length=150, primary_key=True, serialize=False),
        ),
    ]
