# Generated by Django 3.1.2 on 2020-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201020_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='name',
            new_name='watcher_name',
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='zXZEBXUbZMjjHGwEewEgNOabhYhrUInyAhdsWQTwQubmlDpmdXLjwoJVrMyfQzfwZyxROD', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='ueDVrZTdqUKyFvbEgWnqQATggPsNlZMTGZwoZruVYchSrykQIRSBJuYYLILwDoMxKbYPUX', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='bqicuuHmoExxYxZaEaMWpmAZVRBYNgkGadTZThiJNyFZNzRUlNuHdFvfLwozjkDzvBJJNM', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='HWWIEcgjEjRIjvquTkPNjrCvgmYJfCAvItOehTQhNxIshdbBmpiiqphRpBhyQsOKjcxjTL', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='umHIFdRTFvixsRyAaqttLPyScBzUvUcdAGcdPczyruwxPIWSRsosnqGXkWNfQsgWdVJIly', max_length=150, primary_key=True, serialize=False),
        ),
    ]
