# Generated by Django 3.1.2 on 2020-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201020_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='ppXZnWEpPUvUNVGzpLFxiibugnXSJkIAQvgtCICnLbsTqUcwoQCMCBZzxiwSBMOMouhPUg', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='RkwCGLKEdAUEukgGhDNIBzXQVObrJRTuRhmJCqamSoWBNzviUuhbHDgcOpAamjiOcCGvKn', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='NevIYPieNkXXPCsAriKmKYILeutoyMTKnLBanRmCRWwmeUgSpndHRiNvlDGVoVKgNZnKFf', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='NeiRWXkoiuzehiyPDoEFeWOLwGmWtOtIvCQcjtJdlmFExOQcDSnicBPLggPtcYtqHMTLMA', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='LDUajwxaBQyJquWKsYawOdNfCAuCeuysOzYFDHbDFqTdsWlJpRNeGaqlvbUWLSGlGVbKbj', max_length=150, primary_key=True, serialize=False),
        ),
    ]
