# Generated by Django 3.1.2 on 2020-10-24 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201023_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='MnrMdQbwDWYIxsmPNuxiaESLSuAQkxWWbZsGXfEzwCPwpBBNFlPjjCevavErjiSBAlWCIE', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='xYEFrvrpBNhWigoKttNyBldLUICtAPltWIhHeizhsYSnBtydQQybZxkVyiIymAEZGTSAsT', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='HkdSoomImoegHaWrDMtwddeYCEjDAjZeVSkXOTOBEmnoQahvsjxLVssmkUjDFdVtWPptqy', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='JMizWOoRRtGSPshuzvARudVNyhJOrIGKtrWZhOzgreopzyKHHXHoXUFHTHuzztwzbeDqmO', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='aBNagiVlzQKhZMoKiXvGOEvxmSyykZNCGClmqyMNQYbNpgXRCosRgMQygWLosIlCguJUNk', max_length=150, primary_key=True, serialize=False),
        ),
    ]
