# Generated by Django 3.1.2 on 2020-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201024_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='qSOfOxxVvegYzCzvTIaGukWEvglJNMnzXYBKeIkxJctFZveolslGjnOhKIIkmCIqNMmPvR', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='aPXLkccksrhqFtrvlfzIuDXfNYFpUYytfMyPqolMoqdkNvDAghztTttcnBdXcovdiCAvyA', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='WeodeouWpxpIvSQRBjMHzQEUVUuzyAUyxcQxAlVVIDLwrahxXhqdWCXseRvHBeHmtsdyff', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='XuckVWZwuPsyLxEIlMgtBywRKVMjYSiKrrfEhRRENWhkPFmeIJKJZfSJmbcPcWWizWMEPD', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='iQDAdmIWccdYjHNTpQSTrIdptMMWazTqgulKnBSSTQWAVOneEJZmfbUjOHqVbkoZBNjWFX', max_length=150, primary_key=True, serialize=False),
        ),
    ]
