# Generated by Django 3.1.2 on 2020-10-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201024_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='OXnNjkvVeaIwfDWqBXiMTvHMeRcXHIYvmDSefQKMAIeOqIOZPtyaQZnvoyxbQkgKHNCLnJ', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='xFjUXFHONuUzIRwSuVmWHfkQpWBjCFozUCuxTmLCUxUiziUaJQUxHNqvUozjCFKVLbtqFV', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='IsoWkUyqCgOaCzwGzFJbAlfyHNiZGHGPLYLtTPKgjeDxuIwEJNMHvHVRwIDYFXMAgsGRxW', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='sWzkFbHAiWjiuTtFCcRrDwqSuYMhhbFjwkLOuBpZCJWucOJBgSXAmGiSVEpIFiZIUOCoSc', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='pJAANAxMhedEEzlLIEfKWaNOpmuyvrrcauDVDOOOJbFxlTMjKCqbNITpozAZiillBBQBUd', max_length=150, primary_key=True, serialize=False),
        ),
    ]
