# Generated by Django 3.1.2 on 2020-10-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201024_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='YhXQKtExJhCvrDdxYTfeazvOkaGFmRuXAGpbEmLzYFjdBLIGeTzxnFNrPywlzXebCTiKUJ', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='GrHrngLqiklKoovnlNKbQNkLUGcUnnbGLjJirWBcrwMvxdxxIuIEtJvLxfsMjheBbYwkKy', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='ecNkyrZrBInAKZAMaqvzSTcUaJraNMkBQswRIInTDcSXVaDYUJfTvwqQbWvRMQaTnrsLZn', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='made_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='mkLhbiKrYeaghMDciLLhgAwbTuAsUWszlIVmxpTkTyuhtGigmEgBLnEZZNIzrYgRIfvFKx', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='knjTtknEBlxcCfcJFjwwzfbFArUiSlOBNdpdlvPyKXvRKMJTYsHzrZULpuDyyWMuodgxRH', max_length=150, primary_key=True, serialize=False),
        ),
    ]
