# Generated by Django 3.1.2 on 2020-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201025_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='listing_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.CharField(default='UCeSDEpMOQsUYAyaOrfJuRpPAkbKGnhAuSGSEGlvJVhzIakUfsnXrQcUtZjbNPpPFrwjyq', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='WmBegKIMzYOMOgOEPpTlBTZbttNMwEsxlFBGKYPCGZtAKWRGrwYbcPaYLtUtzDViiFiBJv', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='JPzEWIOLphSreWXpncUJWppEqfhxIHoXbXMuWnseoaYlNHDgaqDtbHsbfqPDkkZqhNXvOP', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.CharField(default='hdTaRxXSrQbVLyxzUVeZEvzQNkVhQwbJmlHWpVjSNccCnMLkwcmYEguPgXuQIbMCuzhuvh', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='id',
            field=models.CharField(default='FlSVhUYJOhmFjzpwfaFEbINmWnkYfxjPZdzvVrHhYQnCgolvzYXjYwhdZvHsZlQUeyJOok', max_length=150, primary_key=True, serialize=False),
        ),
    ]
